- name: install libreoffice
  vars:
  block: 
    - name: Add libreoffice repo Centos
      template:
        src: libreoffice7.repo.aq.j2
        dest: /etc/yum.repos.d/libreoffice7.repo
      when: ansible_os_family=="RedHat"

    - name: Install libreoffice packages
      yum:
        name: "{{ item }}"
        state: present
      with_items: 
        - "libobasis7.1-base-7.1.3.2-2.x86_64"
        - "libobasis7.1-calc-7.1.3.2-2.x86_64"
        - "libobasis7.1-core-7.1.3.2-2.x86_64"
        - "libobasis7.1-draw-7.1.3.2-2.x86_64"
        - "libobasis7.1-en-US-7.1.3.2-2.x86_64"
        - "libobasis7.1-extension-beanshell-script-provider-7.1.3.2-2.x86_64"
        - "libobasis7.1-extension-javascript-script-provider-7.1.3.2-2.x86_64"
        - "libobasis7.1-extension-mediawiki-publisher-7.1.3.2-2.x86_64"
        - "libobasis7.1-extension-nlpsolver-7.1.3.2-2.x86_64"
        - "libobasis7.1-extension-pdf-import-7.1.3.2-2.x86_64"
        - "libobasis7.1-extension-report-builder-7.1.3.2-2.x86_64"
        - "libobasis7.1-firebird-7.1.3.2-2.x86_64"
        - "libobasis7.1-gnome-integration-7.1.3.2-2.x86_64"
        - "libobasis7.1-graphicfilter-7.1.3.2-2.x86_64"
        - "libobasis7.1-images-7.1.3.2-2.x86_64"
        - "libobasis7.1-impress-7.1.3.2-2.x86_64"
        - "libobasis7.1-kde-integration-7.1.3.2-2.x86_64"
        - "libobasis7.1-librelogo-7.1.3.2-2.x86_64"
        - "libobasis7.1-libreofficekit-data-7.1.3.2-2.x86_64"
        - "libobasis7.1-math-7.1.3.2-2.x86_64"
        - "libobasis7.1-ogltrans-7.1.3.2-2.x86_64"
        - "libobasis7.1-onlineupdate-7.1.3.2-2.x86_64"
        - "libobasis7.1-ooofonts-7.1.3.2-2.x86_64"
        - "libobasis7.1-ooolinguistic-7.1.3.2-2.x86_64"
        - "libobasis7.1-postgresql-sdbc-7.1.3.2-2.x86_64"
        - "libobasis7.1-python-script-provider-7.1.3.2-2.x86_64"
        - "libobasis7.1-pyuno-7.1.3.2-2.x86_64"
        - "libobasis7.1-writer-7.1.3.2-2.x86_64"
        - "libobasis7.1-xsltfilter-7.1.3.2-2.x86_64"
        - "libreoffice7.1-7.1.3.2-2.x86_64"
        - "libreoffice7.1-base-7.1.3.2-2.x86_64"
        - "libreoffice7.1-calc-7.1.3.2-2.x86_64"
        - "libreoffice7.1-dict-en-7.1.3.2-2.x86_64"
        - "libreoffice7.1-dict-es-7.1.3.2-2.x86_64"
        - "libreoffice7.1-dict-fr-7.1.3.2-2.x86_64"
        - "libreoffice7.1-draw-7.1.3.2-2.x86_64"
        - "libreoffice7.1-en-US-7.1.3.2-2.x86_64"
        - "libreoffice7.1-freedesktop-menus-7.1.3-2.noarch"
        - "libreoffice7.1-impress-7.1.3.2-2.x86_64"
        - "libreoffice7.1-math-7.1.3.2-2.x86_64"
        - "libreoffice7.1-ure-7.1.3.2-2.x86_64"
        - "libreoffice7.1-writer-7.1.3.2-2.x86_64"
