- name: Add nexus repo
  template:
    src: "elk.repo.j2"
    dest: /etc/yum.repos.d/nexus-elk.repo
  when: ansible_os_family=="RedHat"

- name: Install metricbeat
  yum:
    name: metricbeat
    state: latest
  when: ansible_os_family=="RedHat"

- name: Copy config file
  template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
  notify: Configure modules

- name: Enable metricbeat
  systemd:
    name: metricbeat
    state: started
    daemon_reload: yes
    enabled: yes

- name: Configure nginx module
  template:
    src: nginx.yml.j2
    dest: /etc/metricbeat/modules.d/nginx.yml
