- name: Add elk repo Centos
  template:
    src: elk.repo.j2
    dest: /etc/yum.repos.d/elk.repo
  when: ansible_os_family=="RedHat"

- name: Update and upgrade yum packages
  yum:
    name: '*'
    state: latest
    exclude:
      - postgresql*
  when: ansible_os_family=="RedHat"

- name: Update and upgrade apt packages
  apt:
    upgrade: no
    update_cache: no
    force_apt_get: no
    #exclude:
    #  - postgresql*
  when: ansible_os_family=="Debian"
  
- name: check if dotnet in new location exists
  stat:
    path: /usr/local/bin/dotnet
  register: new_dotnet_status 

- name: Create symbolic link dotnet new location
  file:
    src: "/usr/local/bin/dotnet"
    dest: "/usr/bin/dotnet"
    state: link
  when: new_dotnet_status.stat.exists == true
